pipeline {
    agent {
        docker {
            image 'node:lts-bullseye-slim' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install'
                sh 'npm i -D --save-exact mini-css-extract-plugin@2.4.5'
            }
        }
        stage('Test') { 
            steps {
                sh 'chmod +x -R ./jenkins/scripts/test.sh'
                sh './jenkins/scripts/test.sh'  
            }
        }
        stage('Deploy') { 
            steps {
                sh 'chmod +x -R ./jenkins/scripts/deploy.sh'
                sh './jenkins/scripts/deploy.sh' 
                // input message: 'Finished using the web site? (Click "Proceed" to continue)' 
                // sh './jenkins/scripts/kill.sh' 
            }
        }
    }
}